name: CI
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install libbpf-dev libgtest-dev clang-15
      - name: ls som
        run: ls /sys/kernel/debug/tracing/available_events
      - name: ls som2
        run: ls /sys/kernel/tracing/events
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build test binary
        run: make bin/test
      - name: Run tests
        run: sudo make test
    timeout-minutes: 5
