name: CI
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get -y libbpf-dev
      # - name: Build test binary
      #   run: make bin/test
      # - name: Run tests
      #   run: sudo make test
    timeout-minutes: 5
